#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.5456
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="visaVale")]
	public partial class visaValeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVisaVale1(VisaVale1 instance);
    partial void UpdateVisaVale1(VisaVale1 instance);
    partial void DeleteVisaVale1(VisaVale1 instance);
    partial void InsertVisaValeGasto(VisaValeGasto instance);
    partial void UpdateVisaValeGasto(VisaValeGasto instance);
    partial void DeleteVisaValeGasto(VisaValeGasto instance);
    #endregion
		
		public visaValeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
	
		
		public visaValeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		
		
		public System.Data.Linq.Table<VisaVale1> VisaVales
		{
			get
			{
				return this.GetTable<VisaVale1>();
			}
		}
		
		public System.Data.Linq.Table<VisaValeGasto> VisaValeGastos
		{
			get
			{
				return this.GetTable<VisaValeGasto>();
			}
		}
	}
	
	[Table(Name="VisaVale")]
	public partial class VisaVale1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DataConsulta;
		
		private string _NumeroCartao;
		
		private string _DataUltimoBeneficioDataBeneficio;
		
		private string _ValorUltimoBeneficio;
		
		private string _DataProximoBeneficio;
		
		private string _ValorProximoBeneficio;
		
		private string _GetSaldo;
		
		private System.Nullable<bool> _SalvarDados;
		
		private EntitySet<VisaValeGasto> _VisaValeGastos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDataConsultaChanging(string value);
    partial void OnDataConsultaChanged();
    partial void OnNumeroCartaoChanging(string value);
    partial void OnNumeroCartaoChanged();
    partial void OnDataUltimoBeneficioDataBeneficioChanging(string value);
    partial void OnDataUltimoBeneficioDataBeneficioChanged();
    partial void OnValorUltimoBeneficioChanging(string value);
    partial void OnValorUltimoBeneficioChanged();
    partial void OnDataProximoBeneficioChanging(string value);
    partial void OnDataProximoBeneficioChanged();
    partial void OnValorProximoBeneficioChanging(string value);
    partial void OnValorProximoBeneficioChanged();
    partial void OnGetSaldoChanging(string value);
    partial void OnGetSaldoChanged();
    partial void OnSalvarDadosChanging(System.Nullable<bool> value);
    partial void OnSalvarDadosChanged();
    #endregion
		
		public VisaVale1()
		{
			this._VisaValeGastos = new EntitySet<VisaValeGasto>(new Action<VisaValeGasto>(this.attach_VisaValeGastos), new Action<VisaValeGasto>(this.detach_VisaValeGastos));
			OnCreated();
		}
		
		[Column(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_DataConsulta", DbType="NVarChar(100)")]
		public string DataConsulta
		{
			get
			{
				return this._DataConsulta;
			}
			set
			{
				if ((this._DataConsulta != value))
				{
					this.OnDataConsultaChanging(value);
					this.SendPropertyChanging();
					this._DataConsulta = value;
					this.SendPropertyChanged("DataConsulta");
					this.OnDataConsultaChanged();
				}
			}
		}
		
		[Column(Storage="_NumeroCartao", DbType="NVarChar(100)")]
		public string NumeroCartao
		{
			get
			{
				return this._NumeroCartao;
			}
			set
			{
				if ((this._NumeroCartao != value))
				{
					this.OnNumeroCartaoChanging(value);
					this.SendPropertyChanging();
					this._NumeroCartao = value;
					this.SendPropertyChanged("NumeroCartao");
					this.OnNumeroCartaoChanged();
				}
			}
		}
		
		[Column(Storage="_DataUltimoBeneficioDataBeneficio", DbType="NVarChar(100)")]
		public string DataUltimoBeneficioDataBeneficio
		{
			get
			{
				return this._DataUltimoBeneficioDataBeneficio;
			}
			set
			{
				if ((this._DataUltimoBeneficioDataBeneficio != value))
				{
					this.OnDataUltimoBeneficioDataBeneficioChanging(value);
					this.SendPropertyChanging();
					this._DataUltimoBeneficioDataBeneficio = value;
					this.SendPropertyChanged("DataUltimoBeneficioDataBeneficio");
					this.OnDataUltimoBeneficioDataBeneficioChanged();
				}
			}
		}
		
		[Column(Storage="_ValorUltimoBeneficio", DbType="NVarChar(100)")]
		public string ValorUltimoBeneficio
		{
			get
			{
				return this._ValorUltimoBeneficio;
			}
			set
			{
				if ((this._ValorUltimoBeneficio != value))
				{
					this.OnValorUltimoBeneficioChanging(value);
					this.SendPropertyChanging();
					this._ValorUltimoBeneficio = value;
					this.SendPropertyChanged("ValorUltimoBeneficio");
					this.OnValorUltimoBeneficioChanged();
				}
			}
		}
		
		[Column(Storage="_DataProximoBeneficio", DbType="NVarChar(100)")]
		public string DataProximoBeneficio
		{
			get
			{
				return this._DataProximoBeneficio;
			}
			set
			{
				if ((this._DataProximoBeneficio != value))
				{
					this.OnDataProximoBeneficioChanging(value);
					this.SendPropertyChanging();
					this._DataProximoBeneficio = value;
					this.SendPropertyChanged("DataProximoBeneficio");
					this.OnDataProximoBeneficioChanged();
				}
			}
		}
		
		[Column(Storage="_ValorProximoBeneficio", DbType="NVarChar(100)")]
		public string ValorProximoBeneficio
		{
			get
			{
				return this._ValorProximoBeneficio;
			}
			set
			{
				if ((this._ValorProximoBeneficio != value))
				{
					this.OnValorProximoBeneficioChanging(value);
					this.SendPropertyChanging();
					this._ValorProximoBeneficio = value;
					this.SendPropertyChanged("ValorProximoBeneficio");
					this.OnValorProximoBeneficioChanged();
				}
			}
		}
		
		[Column(Name="getSaldo", Storage="_GetSaldo", DbType="NVarChar(100)")]
		public string GetSaldo
		{
			get
			{
				return this._GetSaldo;
			}
			set
			{
				if ((this._GetSaldo != value))
				{
					this.OnGetSaldoChanging(value);
					this.SendPropertyChanging();
					this._GetSaldo = value;
					this.SendPropertyChanged("GetSaldo");
					this.OnGetSaldoChanged();
				}
			}
		}
		
		[Column(Storage="_SalvarDados", DbType="Bit")]
		public System.Nullable<bool> SalvarDados
		{
			get
			{
				return this._SalvarDados;
			}
			set
			{
				if ((this._SalvarDados != value))
				{
					this.OnSalvarDadosChanging(value);
					this.SendPropertyChanging();
					this._SalvarDados = value;
					this.SendPropertyChanged("SalvarDados");
					this.OnSalvarDadosChanged();
				}
			}
		}
		
		[Association(Name="FK_visaVale_visaValeGastos", Storage="_VisaValeGastos", ThisKey="Id", OtherKey="InfoId", DeleteRule="NO ACTION")]
		public EntitySet<VisaValeGasto> VisaValeGastos
		{
			get
			{
				return this._VisaValeGastos;
			}
			set
			{
				this._VisaValeGastos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VisaValeGastos(VisaValeGasto entity)
		{
			this.SendPropertyChanging();
			entity.VisaVale1 = this;
		}
		
		private void detach_VisaValeGastos(VisaValeGasto entity)
		{
			this.SendPropertyChanging();
			entity.VisaVale1 = null;
		}
	}
	
	[Table(Name="visaValeGastos")]
	public partial class VisaValeGasto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Data;
		
		private string _Local;
		
		private string _Valor;
		
		private System.Nullable<int> _InfoId;
		
		private EntityRef<VisaVale1> _VisaVale1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDataChanging(string value);
    partial void OnDataChanged();
    partial void OnLocalChanging(string value);
    partial void OnLocalChanged();
    partial void OnValorChanging(string value);
    partial void OnValorChanged();
    partial void OnInfoIdChanging(System.Nullable<int> value);
    partial void OnInfoIdChanged();
    #endregion
		
		public VisaValeGasto()
		{
			this._VisaVale1 = default(EntityRef<VisaVale1>);
			OnCreated();
		}
		
		[Column(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_Data", DbType="NVarChar(100)")]
		public string Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[Column(Storage="_Local", DbType="NVarChar(100)")]
		public string Local
		{
			get
			{
				return this._Local;
			}
			set
			{
				if ((this._Local != value))
				{
					this.OnLocalChanging(value);
					this.SendPropertyChanging();
					this._Local = value;
					this.SendPropertyChanged("Local");
					this.OnLocalChanged();
				}
			}
		}
		
		[Column(Storage="_Valor", DbType="NVarChar(100)")]
		public string Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[Column(Name="infoId", Storage="_InfoId", DbType="Int")]
		public System.Nullable<int> InfoId
		{
			get
			{
				return this._InfoId;
			}
			set
			{
				if ((this._InfoId != value))
				{
					this.OnInfoIdChanging(value);
					this.SendPropertyChanging();
					this._InfoId = value;
					this.SendPropertyChanged("InfoId");
					this.OnInfoIdChanged();
				}
			}
		}
		
		[Association(Name="FK_visaVale_visaValeGastos", Storage="_VisaVale1", ThisKey="InfoId", OtherKey="Id", IsForeignKey=true)]
		public VisaVale1 VisaVale1
		{
			get
			{
				return this._VisaVale1.Entity;
			}
			set
			{
				VisaVale1 previousValue = this._VisaVale1.Entity;
				if (((previousValue != value) 
							|| (this._VisaVale1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VisaVale1.Entity = null;
						previousValue.VisaValeGastos.Remove(this);
					}
					this._VisaVale1.Entity = value;
					if ((value != null))
					{
						value.VisaValeGastos.Add(this);
						this._InfoId = value.Id;
					}
					else
					{
						this._InfoId = default(Nullable<int>);
					}
					this.SendPropertyChanged("VisaVale1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
